version: 2

builds:
  - id: darwin-amd64
    binary: git-drs
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - codesign --force --options=runtime -s "{{ .Env.APPLE_TEAM_ID }}" "{{ .Path }}"
        - >-
          sh -c 'set -e;
          ZIP_PATH="$(mktemp -t git-drs-notary-XXXXXX).zip";
          trap "rm -f \"$ZIP_PATH\"" EXIT;
          ditto -c -k --keepParent "{{ .Path }}" "$ZIP_PATH";
          xcrun notarytool submit "$ZIP_PATH"
          --apple-id "{{ .Env.APPLE_NOTARY_USER }}"
          --password "{{ .Env.APPLE_NOTARY_PASSWORD }}"
          --team-id "{{ .Env.APPLE_TEAM_ID }}"
          --wait'
  - id: darwin-arm64
    binary: git-drs
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - codesign --force --options=runtime -s "{{ .Env.APPLE_TEAM_ID }}" "{{ .Path }}"
        - >-
          sh -c 'set -e;
          ZIP_PATH="$(mktemp -t git-drs-notary-XXXXXX).zip";
          trap "rm -f \"$ZIP_PATH\"" EXIT;
          ditto -c -k --keepParent "{{ .Path }}" "$ZIP_PATH";
          xcrun notarytool submit "$ZIP_PATH"
          --apple-id "{{ .Env.APPLE_NOTARY_USER }}"
          --password "{{ .Env.APPLE_NOTARY_PASSWORD }}"
          --team-id "{{ .Env.APPLE_TEAM_ID }}"
          --wait'
  - id: linux-amd64
    binary: git-drs
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: linux-arm64
    binary: git-drs
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0

dist: build/release

release:
  draft: false

env_files:
  github_token: .github_token

archives:
  - formats:
      - tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-v{{.Version}}"

    # HACK: Provide a file glob that matches nothing in your directory.
    # This prevents GoReleaser from reverting to default README/LICENSE fallback files.
    files:
      - none*
