builds:
  - binary: git-drs
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dist: build/release

release:
  draft: false

env_files:
  github_token: .github_token

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"

binary_signs:
  - cmd: codesign
    args:
      - "--force"
      - "--options=runtime"
      - "-s"
      - "{{.Env.APPLE_TEAM_ID}}"
      - "${artifact}"
    goos: darwin
    stdin: "{{.Env.APPLE_CERT_PASSWORD}}"
