#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GIT_DRS_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"

ENV_FILE="${ENV_FILE:-$GIT_DRS_ROOT/.env}"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  source "$ENV_FILE"
  set +a
fi

export TEST_SERVER_MODE=local
export TEST_DRS_URL="${TEST_DRS_URL:-${DRS_URL:-http://localhost:8080}}"
export TEST_ORGANIZATION="${TEST_ORGANIZATION:-${ORGANIZATION:-cbdsTest}}"
export TEST_PROJECT_ID="${TEST_PROJECT_ID:-${PROJECT_ID:-${PROJECT:-git_drs_e2e_test}}}"
export TEST_BUCKET="${TEST_BUCKET:-${BUCKET:-cbds}}"
export TEST_CREATE_BUCKET_BEFORE_TEST="${TEST_CREATE_BUCKET_BEFORE_TEST:-${CREATE_BUCKET_BEFORE_TEST:-false}}"
export TEST_BUCKET_NAME="${TEST_BUCKET_NAME:-$TEST_BUCKET}"
export TEST_BUCKET_REGION="${TEST_BUCKET_REGION:-${BUCKET_REGION:-us-east-1}}"
export TEST_BUCKET_ACCESS_KEY="${TEST_BUCKET_ACCESS_KEY:-${BUCKET_ACCESS_KEY:-}}"
export TEST_BUCKET_SECRET_KEY="${TEST_BUCKET_SECRET_KEY:-${BUCKET_SECRET_KEY:-}}"
export TEST_BUCKET_ENDPOINT="${TEST_BUCKET_ENDPOINT:-${BUCKET_ENDPOINT:-}}"
export TEST_DELETE_BUCKET_AFTER="${TEST_DELETE_BUCKET_AFTER:-${DELETE_TEST_BUCKET_AFTER:-false}}"
export TEST_ADMIN_AUTH_HEADER="${TEST_ADMIN_AUTH_HEADER:-${ADMIN_AUTH_HEADER:-}}"
export TEST_LOCAL_USERNAME="${TEST_LOCAL_USERNAME:-${LOCAL_USERNAME:-${DRS_BASIC_AUTH_USER:-}}}"
export TEST_LOCAL_PASSWORD="${TEST_LOCAL_PASSWORD:-${LOCAL_PASSWORD:-${DRS_BASIC_AUTH_PASSWORD:-}}}"

export MONO_REPO_NAME="${MONO_REPO_NAME:-${TEST_REPO_NAME:-git-drs-monorepo-e2e-local}}"
export MONO_WORK_ROOT="${MONO_WORK_ROOT:-${TEST_WORK_ROOT:-$(mktemp -d -t drs-monorepo-local-XXXX)}}"
export MONO_REMOTE_URL="${MONO_REMOTE_URL:-${TEST_REMOTE_URL:-$MONO_WORK_ROOT/${MONO_REPO_NAME}.git}}"
export MONO_DELETE_REMOTE_AT_START="${MONO_DELETE_REMOTE_AT_START:-false}"

exec bash "$SCRIPT_DIR/e2e-monorepo-remote.sh" "$@"
